id: P000570
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG6048
  title: ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་
  author: ''
  volumes:
    12740429800343acba44f3a0e38a39a9:
      image_group_id: I1KG6271
      title: Volume 1 of zhi khro dgongs pa rang grol
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
